# OptiZomb feature flags
opt.glfix=true
opt.glchars=true
opt.bonetbo=true
opt.tileschars=true
opt.batchmerge=true
opt.diagnostics=true

# Zombie render cap (vanilla=510, default=4096)
opt.zombiecap=4096
